### ISSUE TITLE
The Illustrated Word2vec 아티클 리뷰

### ISSUE THREAD

**Issue by syleeie2310** [KaggleBreak/databreak-blog#1]
## Title & Topic
The Illustrated Word2vec

## Upload schedule
2019년 04월 28일까지

## Reference
https://jalammar.github.io/illustrated-word2vec/

**Comment by Gangsss** [comment]
- BERT나 airbnb등 저자가 링크를 걸어 둔 것들이 있는데 그것들을 같이 걸어두시면 좋을 거 같아요!
- 만약 당신이 Siri(시리), 구글 어시스턴트, 알렉사, 구글 번역기, 심지어 스마트폰 키보드에서 다음 단어를 예측한 적이 있다면, 자연어처리 모델의 중심이 된 이 아이디어로부터 무언가 얻을 가능성이 높습니다. - > 다음 단어를 예측하는  Siri(시리), 구글 어시스턴트, 알렉사, 구글 번역기, 심지어 스마트폰 키보드는 자연어 처리 모델의 중심이된 임베딩이 큰 힘이 되었을 것입니다.
- 하지만 사물을 표현하는데 벡터를 이용하는 예제를 들어봅시다

-> 어떤 것을 표현 하는 벡터를 예시로 얘기를 시작하고자합니다

- 다섯 개의 숫자(벡터) 목록이 당신의 성격(MBTI)을 그렇게 많이 표현할 수 있다는 것을 알고 있었나요?

-> 다섯 개의 숫자로 이뤄진 리스트(벡터)로 당신의 성격(MBTI)을 그렇게 많이 표현할 수 있다는 것을 알고 있었나요?

- 고해상도 -> 고해상도라는 표현이 와닿지가 않아서 많은 정보량(고차원) 표현을 통해 라고 하는 것이 나을 거 같아요! 
- 믿을 수 없는 속성 -> 임베딩의 믿을 수 없는 속성
- Word Embedding에서 단어 벡터를 추가하고 빼면 흥미로운 결과를 얻을 수 있습니다. 가장 유명한 예는 “왕”- “남자”+ “여자”라는 공식-> 워드 임베딩들을 더하고 빼면서 흥미로운 결과를 얻을 수 있습니다.  가장 유명한 예시는 “king” - “man” + “woman”이라는 수식 입니다.

**Comment by syleeie2310** [comment]
@Gangsss  감사합니다 강민님 ㅎㅎ 수정했습니다!

꼼꼼히 리뷰해주셔서 감사해요!
