### ISSUE TITLE
Attn: Illustrated Attention

### ISSUE THREAD

**Issue by choco9966** [KaggleBreak/databreak-blog#10]
## Title & Topic

Attention의 내용을 시각화한 자료입니다. 

## Upload schedule

- 작성 시작 날짜 : 5월 12일  
- 업로드 계획 : 5월 20일 

## Reference

원문 : https://towardsdatascience.com/attn-illustrated-attention-5ec4ad276ee3?fbclid=IwAR1_qP1GVFUaFkWOWZNgwIJ__Z9rNP55glOqPec1faEq_GLYAgYSOGhhIvE

**Comment by choco9966** [comment]
번역은 끝났는데, 영어단어 중 어떤 것을 한글로 번역하고 영어 그 자체로 냅둘지 힘드네요 ㅠ_ㅠ

**Comment by syleeie2310** [comment]
@choco9966 님 5월 꺼 끝났으면 @Youngpyoryu 님한테 리뷰 받으시면 됩니다!

**Comment by syleeie2310** [comment]
위에 댓글은 무시하심 됩니다. 번호를 착각해서 @choco9966 님 5월달 꺼 완료하면 @Gangsss  님한테 받으시면 됩니다.!

**Comment by Gangsss** [comment]
그림 0.2 0.1 이런 거가 어떤 걸 말하는 지 헷갈릴 수 있을 거 같아요 
그림 순서를 알려주시면 좋을 거 같아요

번역어투
이게 다야 -> 이것이 전부입니다

**Comment by choco9966** [comment]
이미지 내부에는 순서를 적어놨는데, 이를 밖으로 빼면 보기가 흉해지는? 문제가 생기더라구요 ㅠㅠ 이 부분은 좀 더 연구를 해보고 고쳐볼게요
