### ISSUE TITLE
Feature Selection with Null Importances

### ISSUE THREAD

**Issue by choco9966** [KaggleBreak/databreak-blog#3]
## Title & Topic

캐글에서 점수를 올리기 위해서 변수제거(선택)법을 많이 사용합니다. 그 중에서 Target과 연관지어서 사용하는 Null importance라는 기법에 대해서 정리해보도록 하겠습니다. 

## Upload schedule

작성 시작 날짜 : 4월 7일 
업로드 날짜 : 4월 14일

## Reference

자료 : https://www.kaggle.com/ogrellier/feature-selection-with-null-importances

**Comment by syleeie2310** [comment]
@choco9966 님 정리하느라 고생하셨어요 ㅎㅎ

내용 되게 좋은데 가독성 있게 좀 수정하는게 어떨까 싶어요. 띄어쓰기도 중간에 좀 넣고..

1) 제일 위에 있는 화면 이미지 크기 줄여주세요! (이미지 파일 크기를 줄이거나)

2) Null Importance Feature Selection은 실제 변수의 중요도와 임의로 셔플된 목적변수의 변수중요도의 분포를 비교하는 방법입니다.

=>
Null Importance Feature Selection
- 실제 변수의 중요도와 임의로 셔플된 목적변수의 변수 중요도의 분포를 비교하는 방법입니다.

=> 글씨 크기 한개만 줄여주세요. 여기 글씨가 너무 커서요 ㅋㅋ 그리고 줄을 나누는게 어떨까 싶어요 가독성 때문에 


3) 원래의 논문에서는 변수의 실제 중요도에 관해 이야기하지 않지만, 변수가 실제로 가지는 변수중요도 값을 같이 이해해야 한다고 생각합니다.
=> 원래의 논문에서는 변수의 실제 중요도에 관해 이야기하지 않지만, 변수가 실제로 가지는 변수 중요도 값을 같이 이해해야 한다고 생각합니다.


4) 상관 된 변수들은 변수 중 하나가 사용되면 다른 하나는 부패한 중요도를 가집니다. 선택된 기능은 매우 중요하며 관련 변수는 부패한 중요도를 갖습니다.
=> 	상관 관계가 있는 변수들은 변수 중 하나가 사용되면 다른 하나는 중요도가 Decay 됩니다. 선택된 기능은 매우 중요하며 관련 변수는 중요도가 Decay 됩니다.

이게 애매하긴 했는데 부패하다고 표현하는 건 좀 아닌거 같고, 좋은 표현 있으면 바꿔주세요!




그리고 수정 완료되면 페이스북에 올려주세요!  
페이스북 포스팅 할 때는 다른 분들이 쓰신 것처럼 이번 아티클 보면서 얻은 개인적인 인사이트 & 대상자 명시해주세요.

**Comment by choco9966** [comment]
> 이게 애매하긴 했는데 부패하다고 표현하는 건 좀 아닌거 같고, 좋은 표현 있으면 바꿔주세요! 

ㅋㅋㅋㅋㅋㅋ 이 부분이 저도 번역하면서 제일 힘들었는데, 상관있는 변수 중 하나가 선택되면 중요했던 변수가 중요해지지 않는다고 표현한건데 그냥 풀어서 써야겠네요.  

사진의 경우 단순히 이미지 파일 크기 줄인다고 수정되지 않네요. 이건 좀 더 테스트 해볼게요

다른 부분은 언능 수정할게요!!
