### ISSUE TITLE
The Power of Bayesian A/B Testing 포스트 번역

### ISSUE THREAD

**Issue by kaylee123** [KaggleBreak/databreak-blog#4]
## Title & Topic

 - Bayesian
 - A/B testing 

## Upload schedule

- 작성시작날짜 : 2019/04/05
- 업로드계획 : 2019/04/13

## Reference

https://medium.com/convoy-tech/the-power-of-bayesian-a-b-testing-f859d2219d5

**Comment by syleeie2310** [comment]
@RyanYS   님 리뷰해주시면 됩니다. 리뷰하고 수정하신 다음에 @kaylee123 님 페이스북 포스팅 해주시면 됩니다.

페이스북 포스팅 가이드는 아래 참고하세요.!
 https://github.com/KaggleBreak/databreak-blog/blob/master/GUIDELINE.md

**Comment by RyanYS** [comment]
@kaylee123 님 어려운 주제 번역 하시느라 고생 많으셨습니다.
딱히 눈에 걸리는 문장들은 보이지 않아, 오타 위주로 리뷰 드렸습니다.

#  

이상적이지 않다고 -> 이상적이지 않는다고
왜냐하면 더 빨리 -> 왜냐하면, 더 빨리
AB테스트를 -> AB 테스트를
가속화할 -> 가속할
희생없이 -> 희생 없이
흔히쓰는방법 -> 흔히 쓰는 방법 - 여러 개 (베이지안과의 비교기 때문에 빈도주의 방법? 등도 괜찮을 것 같습니다.)
포스틍에서 -> 포스트에서
믿음(prior)를 -> 믿음(prior)을
해석가능한 -> 해석 가능한
몇년 -> 몇 년
B테스트는 -> B 테스트는
흔히하는절차의 -> 흔히 하는 절차의
베이지안방법론 -> 베이지안 방법론
작을때 -> 작을 때
α가됩니다 -> α가 됩니다
아무 것도 -> 아무것도
왜냐하면 α와 -> 왜냐하면, α와
관찰 할 -> 관찰할
두가지 -> 두 가지
불확실한다면 -> 불확실하다면
α 일 때 -> α일 때
할만큼 -> 할 만큼
첫번째 -> 첫 번째
또다른 -> 또 다른
몇가지 -> 몇 가지
대해이 -> 대해 이
확신 할 -> 확신할
집어 넣은 -> 집어넣은
도달하는데 필요한 -> 도달하는 데 필요한
있을만큼 -> 있을 만큼
선택하는데 있어 -> 선택하는 데 있어
의사결정력이 -> 의사 결정력이
나올만큼 -> 나올 만큼
알게할 수있습니다 -> 알게 할 수 있습니다.
너의 결정이 -> 당신의 결정이
이 그래프는 베이지안 A/B 테스트가 제공하는 보장을 보여준다. -> 보여줍니다.
베이지안 분석의 비평가들은 사전 분포의 선택이 충분히 타당하지 않았다는 것으로 주장할 수 있다. 사실, 이전 섹션에서 제시한 시뮬레이션은 완벽한 사전 분포를 사용한다고 가정했다. -> 각각, 입니다, 가정합니다.
제일 마지막 두 문장은 이다. 로 끝납니다.

고생 많으셨습니다.
