### ISSUE TITLE
Spark ML의 Model Parallelism

### ISSUE THREAD

**Issue by Swalloow** [KaggleBreak/databreak-blog#8]
## Title & Topic
- Spark ML의 Model Parallelism

## Upload schedule
- 2019-04-28 ~ 2019-05-10

## Reference
- https://bryancutler.github.io/cv-parallel/
- https://www.youtube.com/watch?v=UoZYujwaGGA

**Comment by syleeie2310** [comment]
@Swalloow 님 이거 4~5월 꺼로 그냥 퉁쳐서 마무리 해주세요.. 완료하시면 @Gangsss 님한테 리뷰 받으시면 됩니다!!

**Comment by syleeie2310** [comment]
위에 댓글은 무시하심 됩니다. 번호를 착각해서 @Swalloow 님 5월달 꺼 완료하면 조영승님한테 받으시면 됩니다.!
