### ISSUE TITLE
Best Data and Big Data Visualization Techniques(#9)

### ISSUE THREAD

**Issue by Gangsss** [KaggleBreak/databreak-blog#9]
## Title & Topic
Best Data and Big Data Visualization Techniques

## Upload schedule
5월 5일 1차 업로드 - 리뷰 받은 후 2차 업로드

## Reference
https://medium.com/sciforce/best-data-and-big-data-visualization-techniques-e07b897751dd

**Comment by inahjeon** [comment]
띄어쓰기 및 오탈자 관련 입니다.

- 파이 와 도넛 차트의 -> 파이와 도넛 차트의 

- 인간의 눈은 넓이을 추정하고 -> 인간의 눈은 넓이를 추정하고

- 구성한느 투플의 수 -> 구성하는 튜플의 수

**Comment by Gangsss** [comment]
감사합니다!
